var data = [
  {
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._01_-_Autorretrato._Francisco_Goya_y_Lucientes2C_pintor.jpg",
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._01_-_Autorretrato._Francisco_Goya_y_Lucientes2C_pintor_thumb.jpg",
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Francisco Goya y Lucientes, painter</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Francisco Goya y Lucientes, painter</span><br><span class=\"goya-lightbox__title--spanish\">Francisco Goya y Lucientes, pintor</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 15.1 cm (8.5 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._02_-_El_si_pronuncian_y_la_mano_alargan_al_primero_que_llega.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._02_-_El_si_pronuncian_y_la_mano_alargan_al_primero_que_llega_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">They say yes and give their hand to the first comer</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">They say yes and give their hand to the first comer</span><br><span class=\"goya-lightbox__title--spanish\">El s\u00ed pronuncian y la mano alargan al primero que llega</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 15.3 cm (8.5 \u00d7 6 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._03_-_Que_viene_el_Coco.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._03_-_Que_viene_el_Coco_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Here comes the bogeyman</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Here comes the bogeyman</span><br><span class=\"goya-lightbox__title--spanish\">Que viene el coco</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.4 \u00d7 15.2 cm (8.4 \u00d7 6 in) (print)/ 30,6 x 20,1 cm (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._04_-_El_de_la_rollona.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._04_-_El_de_la_rollona_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Nanny's boy</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Nanny's boy</span><br><span class=\"goya-lightbox__title--spanish\">El de la Rollona</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">20.5 \u00d7 15 cm (8.1 \u00d7 5.9 in) (print)/ 30,6 x 20,1 cm (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._05_-_Tal_para_qual.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._05_-_Tal_para_qual_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Two of a kind</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Two of a kind</span><br><span class=\"goya-lightbox__title--spanish\">Tal para cual</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">19.8 \u00d7 15 cm (7.8 \u00d7 5.9 in). (Picture) / 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._06_-_Nadie_se_conoce.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._06_-_Nadie_se_conoce_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Nobody knows himself</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Nobody knows himself</span><br><span class=\"goya-lightbox__title--spanish\">Nadie se conoce</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.4 \u00d7 15.2 cm (8.4 \u00d7 6 in). (Picture) / 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._07_-_Ni_asi_la_distingue.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._07_-_Ni_asi_la_distingue_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Even thus he cannot make her out</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Even thus he cannot make her out</span><br><span class=\"goya-lightbox__title--spanish\">Ni as\u00ed la distingue</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">19.7 \u00d7 14.9 cm (7.8 \u00d7 5.9 in). (Picture) / 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._08_-_Que_se_la_llevaron21.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._08_-_Que_se_la_llevaron21_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">So they carried her off!</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">So they carried her off!</span><br><span class=\"goya-lightbox__title--spanish\">\u00a1Que se la llevaron!</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.4 \u00d7 15 cm (8.4 \u00d7 5.9 in). (Picture) / 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._09_-_Tantalo.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._09_-_Tantalo_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Tantalus</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Tantalus</span><br><span class=\"goya-lightbox__title--spanish\">T\u00e1ntalo</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">20.5 \u00d7 14.9 cm (8.1 \u00d7 5.9 in). (Picture) / 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._10_-_El_amor_y_la_muerte.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._10_-_El_amor_y_la_muerte_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Love and death</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Love and death</span><br><span class=\"goya-lightbox__title--spanish\">El amor y la muerte</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 15.1 cm (8.5 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._11_-_Muchachos_al_avC3ADo.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._11_-_Muchachos_al_avC3ADo_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Lads making ready</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Lads making ready</span><br><span class=\"goya-lightbox__title--spanish\">Muchachos al av\u00edo</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 15.2 cm (8.5 \u00d7 6 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._12_-_A_caza_de_dientes.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._12_-_A_caza_de_dientes_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Out hunting for teeth</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Out hunting for teeth</span><br><span class=\"goya-lightbox__title--spanish\">A caza de dientes</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 15 cm (8.5 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._13_-_Estan_calientes.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._13_-_Estan_calientes_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">They are hot</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">They are hot</span><br><span class=\"goya-lightbox__title--spanish\">Est\u00e1n calientes</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.4 \u00d7 15.2 cm (8.4 \u00d7 6 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._14_-_Que_sacrificio21.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._14_-_Que_sacrificio21_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">What a sacrifice!</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">What a sacrifice!</span><br><span class=\"goya-lightbox__title--spanish\">\u00a1Qu\u00e9 sacrificio!</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">19.8 \u00d7 14.8 cm (7.8 \u00d7 5.8 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._15_-_Bellos_consejos.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._15_-_Bellos_consejos_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Good advice</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Good advice</span><br><span class=\"goya-lightbox__title--spanish\">Bellos consejos</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 15.1 cm (8.5 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._16_-_Dios_la_perdone_-_Y_era_su_madre.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._16_-_Dios_la_perdone_-_Y_era_su_madre_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">For Heaven's sake: and it was her mother</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">For Heaven's sake: and it was her mother</span><br><span class=\"goya-lightbox__title--spanish\">Dios la perdone: y era su madre</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">19.8 \u00d7 14.9 cm (7.8 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._17_-_Bien_tirada_estC3A1.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._17_-_Bien_tirada_estC3A1_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">To the count palatine</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">It is nicely stretched</span><br><span class=\"goya-lightbox__title--spanish\">Bien tirada est\u00e1</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 15.1 cm (8.5 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._18_-_Y_se_le_quema_la_Casa.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._18_-_Y_se_le_quema_la_Casa_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Sleep overcomes them</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">And the house is on fire</span><br><span class=\"goya-lightbox__title--spanish\">Y se le quema la casa</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.6 \u00d7 15.2 cm (8.5 \u00d7 6 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._19_-_Todos_CaerC3A1n.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._19_-_Todos_CaerC3A1n_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">She fleeces him</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Everyone will fall</span><br><span class=\"goya-lightbox__title--spanish\">Todos caer\u00e1n</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 14.4 cm (8.5 \u00d7 5.7 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._20_-_Ya_van_desplumados.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._20_-_Ya_van_desplumados_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">A bad night</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">There they go plucked</span><br><span class=\"goya-lightbox__title--spanish\">Ya van desplumados</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 15.1 cm (8.5 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._21_-_C2A1Qual_la_descaC3B1onan21.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._21_-_C2A1Qual_la_descaC3B1onan21_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Might not the pupil know more?</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">How they pluck her!</span><br><span class=\"goya-lightbox__title--spanish\">\u00a1Cual la desca\u00f1onan!</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 14.7 cm (8.5 \u00d7 5.8 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._22_-_Pobrecitas21.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._22_-_Pobrecitas21_thumb.jpg", 
    "hoverDescription": "",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Poor little girls!</span><br><span class=\"goya-lightbox__title--spanish\">\u00a1Pobrecitas!</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 15.2 cm (8.5 \u00d7 6 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._23_-_Aquellos_polbos.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._23_-_Aquellos_polbos_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">It is nicely stretched</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Those specks of dust</span><br><span class=\"goya-lightbox__title--spanish\">Aquellos polvos</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 14.7 cm (8.5 \u00d7 5.8 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._24_-_No_hubo_remedio.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._24_-_No_hubo_remedio_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">And the house is on fire</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">There was no help</span><br><span class=\"goya-lightbox__title--spanish\">No hubo remedio</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 15 cm (8.5 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._25_-_Si_quebrC3B3_el_Cantaro.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._25_-_Si_quebrC3B3_el_Cantaro_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Everyone will fall</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">He broke the pitcher</span><br><span class=\"goya-lightbox__title--spanish\">Si quebr\u00f3 el c\u00e1ntaro</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">20.6 \u00d7 15.1 cm (8.1 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._26_-_Ya_tienen_asiento.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._26_-_Ya_tienen_asiento_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">There they go plucked</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Now they are sitting well</span><br><span class=\"goya-lightbox__title--spanish\">Ya tienen asiento</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 15.1 cm (8.5 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._27_-_Quien_mC3A1s_rendido3F.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._27_-_Quien_mC3A1s_rendido3F_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">How they pluck her!</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Who more is surrendered?</span><br><span class=\"goya-lightbox__title--spanish\">\u00bfQui\u00e9n m\u00e1s rendido?</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">19.3 \u00d7 14.9 cm (7.6 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._28_-_Chiton.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._28_-_Chiton_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Poor little girls!</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Hush</span><br><span class=\"goya-lightbox__title--spanish\">Chit\u00f3n</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 15.1 cm (8.5 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._29_-_Esto_si_que_es_leer.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._29_-_Esto_si_que_es_leer_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Those specks of dust</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Now that's reading</span><br><span class=\"goya-lightbox__title--spanish\">Esto s\u00ed que es leer</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.4 \u00d7 14.6 cm (8.4 \u00d7 5.7 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._30_-_Porque_esconderlos3F.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._30_-_Porque_esconderlos3F_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">There was no help</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Why hide them?</span><br><span class=\"goya-lightbox__title--spanish\">\u00bfPor qu\u00e9 esconderlos?</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 15.1 cm (8.5 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._31_-_Ruega_por_ella.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._31_-_Ruega_por_ella_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Now that's reading</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">She prays for her</span><br><span class=\"goya-lightbox__title--spanish\">Ruega por ella</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">20.5 \u00d7 15 cm (8.1 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._32_-_Por_que_fue_sensible.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._32_-_Por_que_fue_sensible_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Hush</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Because she was susceptible</span><br><span class=\"goya-lightbox__title--spanish\">Porque fue sensible</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.4 \u00d7 15 cm (8.4 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._33_-_Al_Conde_Palatino.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._33_-_Al_Conde_Palatino_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Who more is surrendered?</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">To the count palatine</span><br><span class=\"goya-lightbox__title--spanish\">Al conde palatino</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.4 \u00d7 15.2 cm (8.4 \u00d7 6 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._34_-_Las_rinde_el_SueC3B1o.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._34_-_Las_rinde_el_SueC3B1o_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Now they are sitting well</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Sleep overcomes them</span><br><span class=\"goya-lightbox__title--spanish\">Las rinde el sue\u00f1o</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 15.2 cm (8.5 \u00d7 6 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._35_-_Le_descaC3B1ona.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._35_-_Le_descaC3B1ona_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">He broke the pitcher</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">She fleeces him</span><br><span class=\"goya-lightbox__title--spanish\">Le desca\u00f1ona</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.4 \u00d7 15.2 cm (8.4 \u00d7 6 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._36_-_Mala_noche.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._36_-_Mala_noche_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Why hide them?</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">A bad night</span><br><span class=\"goya-lightbox__title--spanish\">Mala noche</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.3 \u00d7 15.1 cm (8.4 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._37_-_Si_sabrC3A1_mas_el_discipulo3F.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._37_-_Si_sabrC3A1_mas_el_discipulo3F_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">She prays for her</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Might not the pupil know more?</span><br><span class=\"goya-lightbox__title--spanish\">\u00bfSi sabra m\u00e1s el disc\u00edpulo?</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.5 \u00d7 15 cm (8.5 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._38_-_Brabisimo21.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._38_-_Brabisimo21_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Because she was susceptible</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Bravissimo!</span><br><span class=\"goya-lightbox__title--spanish\">\u00a1Brav\u00edsimo!</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.4 \u00d7 15 cm (8.4 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._39_-_Asta_su_Abuelo.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._39_-_Asta_su_Abuelo_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">What a golden beak!</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">And so was his grandfather</span><br><span class=\"goya-lightbox__title--spanish\">Hasta su abuelo</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.4 \u00d7 14.9 cm (8.4 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._40_-_De_que_mal_morira3F.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._40_-_De_que_mal_morira3F_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">What a tailor can do!</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Of what ill will he die?</span><br><span class=\"goya-lightbox__title--spanish\">\u00bfDe qu\u00e9 mal morir\u00e1?</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">19.7 \u00d7 14.9 cm (7.8 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._41_-_Ni_mas_ni_menos.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._41_-_Ni_mas_ni_menos_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">They spruce themselves up</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Neither more nor less</span><br><span class=\"goya-lightbox__title--spanish\">Ni m\u00e1s ni menos</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.3 \u00d7 15.2 cm (8.4 \u00d7 6 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._42_-_Tu_que_no_puedes.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._42_-_Tu_que_no_puedes_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">The Chinchillas</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Thou who cannot</span><br><span class=\"goya-lightbox__title--spanish\">T\u00fa que no puedes</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span><br><span class=\"goya-lightbox__detail__heading\">Size</span><br><span class=\"goya-lightbox__detail__content\">21.3 \u00d7 15.1 cm (8.4 \u00d7 5.9 in). (print)/ 30,6 x 20,1 cm. (paper)</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._43_-_El_sueC3B1o_de_la_razon_produce_monstruos.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._43_-_El_sueC3B1o_de_la_razon_produce_monstruos_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Hobgoblins</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">The Sleep of Reason Produces Monsters</span><br><span class=\"goya-lightbox__title--spanish\">El sue\u00f1o de la raz\u00f3n produce monstruos</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._44_-_Hilan_delgado.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._44_-_Hilan_delgado_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Bravissimo!</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">They spin finely</span><br><span class=\"goya-lightbox__title--spanish\">Hilan delgado</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._45_-_Mucho_hay_que_chupar.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._45_-_Mucho_hay_que_chupar_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">And so was his grandfather</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">There is plenty to suck</span><br><span class=\"goya-lightbox__title--spanish\">Mucho hay que chupar</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._46_-_Correccion.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._46_-_Correccion_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Of what ill will he die?</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Correction</span><br><span class=\"goya-lightbox__title--spanish\">Correcci\u00f3n</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._47_-_Obsequio_C3A1_el_maestro.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._47_-_Obsequio_C3A1_el_maestro_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Neither more nor less</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">A gift for the master</span><br><span class=\"goya-lightbox__title--spanish\">Obsequio al maestro</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._48_-_Soplones.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._48_-_Soplones_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Thou who cannot</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Big gusts</span><br><span class=\"goya-lightbox__title--spanish\">Soplones</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._49_-_Duendecitos.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._49_-_Duendecitos_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">The Sleep of Reason Produces Monsters</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Hobgoblins</span><br><span class=\"goya-lightbox__title--spanish\">Duendecitos</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._50_-_Los_Chinchillas.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._50_-_Los_Chinchillas_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">They spin finely</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">The Chinchillas</span><br><span class=\"goya-lightbox__title--spanish\">Los Chinchillas</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._51_-_Se_repulen.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._51_-_Se_repulen_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">There is plenty to suck</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">They spruce themselves up</span><br><span class=\"goya-lightbox__title--spanish\">Se repulen</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._52_-_Lo_que_puede_un_Sastre21.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._52_-_Lo_que_puede_un_Sastre21_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Correction</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">What a tailor can do!</span><br><span class=\"goya-lightbox__title--spanish\">\u00a1Lo que puede un sastre!</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._53_-_Que_pico_de_Oro21.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._53_-_Que_pico_de_Oro21_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">A gift for the master</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">What a golden beak!</span><br><span class=\"goya-lightbox__title--spanish\">\u00a1Que pico de oro!</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._54_-_El_Vergonzoso.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._54_-_El_Vergonzoso_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Big gusts</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">The shameful one</span><br><span class=\"goya-lightbox__title--spanish\">El vergonzoso</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._55_-_Hasta_la_muerte.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._55_-_Hasta_la_muerte_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">What one does to the other</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Until death</span><br><span class=\"goya-lightbox__title--spanish\">Hasta la muerte</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._56_-_Subir_y_bajar.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._56_-_Subir_y_bajar_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">You understand?... Well, as I say... eh! Look out! Otherwise...</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">To rise and to fall</span><br><span class=\"goya-lightbox__title--spanish\">Subir y bajar</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._57_-_La_filiacion.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._57_-_La_filiacion_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Can't anyone unleash us?</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">The filiation</span><br><span class=\"goya-lightbox__title--spanish\">La filiaci\u00f3n</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._58_-_Tragala_perro.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._58_-_Tragala_perro_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Don't scream, stupid</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Swallow it, dog</span><br><span class=\"goya-lightbox__title--spanish\">Tr\u00e1gala, perro</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._59_-_Y_aun_no_se_van21.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._59_-_Y_aun_no_se_van21_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">It is better to be lazy</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">And still they don't go!</span><br><span class=\"goya-lightbox__title--spanish\">\u00a1Y a\u00fan no se van!</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._60_-_Ensayos.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._60_-_Ensayos_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">The shameful one</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Trials</span><br><span class=\"goya-lightbox__title--spanish\">Ensayos</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._61_-_Volaverunt.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._61_-_Volaverunt_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Until death</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">They have flown</span><br><span class=\"goya-lightbox__title--spanish\">Volav\u00e9runt</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._62_-_Quien_lo_creyera21.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._62_-_Quien_lo_creyera21_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">To rise and to fall</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Who would have thought it!</span><br><span class=\"goya-lightbox__title--spanish\">\u00a1Qui\u00e9n lo creyera!</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._63_-_Miren_que_grabes21.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._63_-_Miren_que_grabes21_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">The filiation</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Look how solemn they are!</span><br><span class=\"goya-lightbox__title--spanish\">\u00a1Miren que graves!</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._64_-_Buen_Viage.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._64_-_Buen_Viage_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Swallow it, dog</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Bon voyage</span><br><span class=\"goya-lightbox__title--spanish\">Buen viaje</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._65_-_Donde_vC3A1_mamC3A13F.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._65_-_Donde_vC3A1_mamC3A13F_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">And still they don't go!</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Where is mommy going?</span><br><span class=\"goya-lightbox__title--spanish\">\u00bfD\u00f3nde va mam\u00e1?</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._66_-_AllC3A1_vC3A1_eso.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._66_-_AllC3A1_vC3A1_eso_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Trials</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">There it goes</span><br><span class=\"goya-lightbox__title--spanish\">All\u00e1 va eso</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._67_-_Aguarda_que_te_unten.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._67_-_Aguarda_que_te_unten_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">They have flown</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Wait till you've been anointed</span><br><span class=\"goya-lightbox__title--spanish\">Aguarda que te unten</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._68_-_Linda_maestra21.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._68_-_Linda_maestra21_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Who would have thought it!</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Pretty teacher</span><br><span class=\"goya-lightbox__title--spanish\">Linda maestra</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._69_-_Sopla.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._69_-_Sopla_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Look how solemn they are!</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Gust the wind</span><br><span class=\"goya-lightbox__title--spanish\">Sopla</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._70_-_Devota_profesion.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._70_-_Devota_profesion_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Bon voyage</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Devout profession</span><br><span class=\"goya-lightbox__title--spanish\">Devota profesi\u00f3n</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._71_-_Si_amanece2C_nos_Vamos.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._71_-_Si_amanece2C_nos_Vamos_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Where is mommy going?</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">When day breaks we will be off</span><br><span class=\"goya-lightbox__title--spanish\">Si amanece, nos vamos</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._72_-_No_te_escaparC3A1s.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._72_-_No_te_escaparC3A1s_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">There it goes</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">You will not escape</span><br><span class=\"goya-lightbox__title--spanish\">No te escapar\u00e1s</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._73_-_Mejor_es_holgar.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._73_-_Mejor_es_holgar_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Wait till you've been anointed</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">It is better to be lazy</span><br><span class=\"goya-lightbox__title--spanish\">Mejor es holgar</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._74_-_No_grites2C_tonta.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._74_-_No_grites2C_tonta_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Pretty teacher</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Don't scream, stupid</span><br><span class=\"goya-lightbox__title--spanish\">No grites, tonta</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._75_-_C2BFNo_hay_quien_nos_desate3F.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._75_-_C2BFNo_hay_quien_nos_desate3F_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Gust the wind</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Can't anyone unleash us?</span><br><span class=\"goya-lightbox__title--spanish\">\u00bfNo hay qui\u00e9n nos desate?</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._76_-_C2BFEstC3A1_VmE280A6_pues2C_Como_digoE280A6_eh21_Cuidado21_si_no21.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._76_-_C2BFEstC3A1_VmE280A6_pues2C_Como_digoE280A6_eh21_Cuidado21_si_no21_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">Devout profession</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">You understand?... Well, as I say... eh! Look out! Otherwise...</span><br><span class=\"goya-lightbox__title--spanish\">Est\u00e1 vuestra merced... pues, como digo... \u00a1eh! \u00a1cuidado! si no...</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._77_-_Unos_C3A1_otros.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._77_-_Unos_C3A1_otros_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">When day breaks we will be off</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">What one does to the other</span><br><span class=\"goya-lightbox__title--spanish\">Unos a otros</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._78_-_Despacha2C_que_dispiC3A9rtan.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._78_-_Despacha2C_que_dispiC3A9rtan_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">You will not escape</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">Be quick, they are waking up</span><br><span class=\"goya-lightbox__title--spanish\">Despacha, que despiertan</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._79_-_Nadie_nos_ha_visto.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._79_-_Nadie_nos_ha_visto_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">No one has seen us</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">No one has seen us</span><br><span class=\"goya-lightbox__title--spanish\">Nadie nos ha visto</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  },{
    "imageURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._80_-_Ya_es_hora.jpg", 
    "thumbnailURL": "https://s3-us-west-2.amazonaws.com/famous-framework/lightbox/caprichos/Museo_del_Prado_-_Goya_-_Caprichos_-_No._80_-_Ya_es_hora_thumb.jpg", 
    "hoverDescription": "<span class=\"goya-lightbox__thumb__title\">It is time</span><br><span class=\"goya-lightbox__thumb__year\">1797-1799</span></div>",
    "detailTitle": "<span class=\"goya-lightbox__title--english\">It is time</span><br><span class=\"goya-lightbox__title--spanish\">Ya es hora</span>",
    "detailDescription": "<span class=\"goya-lightbox__detail__heading\">Series</span><br><span class=\"goya-lightbox__detail__content\">Capricho 42</span><br><span class=\"goya-lightbox__detail__heading\">Artist</span><br><span class=\"goya-lightbox__detail__content\">Francisco Goya y Lucientes (Spain, Fuendetodos, 1746-1828)</span><br><span class=\"goya-lightbox__detail__heading\">Date</span><br><span class=\"goya-lightbox__detail__content\">Spain, 1799</span>"
  }
]

module.exports = data;